mineflayer = require('mineflayer')

const options = {
  host: 'game2.falixserver.net', // Change this to the ip you want.
  port: 27493 // Change this to the port you want.
}
setInterval(function() {
    const bot = mineflayer.createBot(options)

}, 60 * 1000);                                    
// 60 * 1000 milsec
